### ISSUE TITLE
Scope changes...

### ISSUE THREAD

**Issue by AnitaGrowsoon** [AnitaGrowsoon/PmonVsMK#5]
Ok. I have a button that pulls some information when it's clicked. SOMETIMES! it throws an error, and SOMETIMES it doesn't!. Same button. I just click it multiple times and eventually it will work. It reads the information..sometimes, but what can I do to make sure it reads the info ALL the time!? it's maddening.

Here is a screenshot, 5 times in a row, it didn't recognize, then another 2 times, and then it worked just fine. No idea why. 

it's the "uncaught error: cannot read property 1 of undefined." 
That's an error I understand. It means the scope is off so the parameters I'm passing in aren't being interpreted correctly, but... then sometimes they are (as seen in this screenshot where "yourCard" is being read just fine, and the console log that shows the steps have gone through with no error.).

<img width="1074" alt="screen shot 2015-10-18 at 9 55 45 am" src="https://cloud.githubusercontent.com/assets/13145686/10564353/d6562d0c-757e-11e5-8161-8907559f2850.png">

**Comment by AnitaGrowsoon** [comment]
rewrote the function as part of a module and negated the scoping issue

**Comment by AnitaGrowsoon** [comment]
rewrote the function as part of a module and negated the scoping issue

**Comment by sssyed** [comment]
@AnitaGrowsoon :+1:
